name: Manually Unzip Multi-part Zip Files

on: 
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Unzip
      run: sudo apt-get install unzip

    - name: Unzip Multi-part Zip Files
      run: |
        set -e
        cd checkpoints
        for file in *.zip.001; do
          zipname=$(echo $file | sed 's/.001$//')
          unzip -FF "$zipname".zip.001
        done
